# Generated by Django 3.2.5 on 2021-07-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commenter',
            table='commenter',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='items',
            table='items',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table='subscribe',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
