# Generated by Django 3.2.5 on 2021-07-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='course',
            name='description_2',
            field=models.TextField(null=True),
        ),
    ]
