# Generated by Django 3.2.5 on 2021-07-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_commenter_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenter',
            name='image',
        ),
    ]
